name: Generate Snake Animation

on:
  schedule:
    - cron: "0 23 * * *" # roda todo dia às 23h UTC
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main # se sua branch principal for "master", troque aqui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: pedrxzz1
          outputs: dist/snake.svg

      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
