name: Generate Snake Animation

on:
  schedule: # roda todo dia às 23h UTC
    - cron: "0 23 * * *"
  workflow_dispatch: # permite rodar manualmente
  push: # roda sempre que tiver push na main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: pedrxzz1
          outputs: dist/snake.svg

      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
